---
title: "Plots"
output: github_document
---

```{r}

library(tidyverse)

#load in group data

all_seh = read.csv("data/all_seh.csv")
all_sef = read.csv("data/all_sef.csv")
all_esf = read.csv("data/all_esf.csv")
all_esh = read.csv("data/all_esh.csv")

all_se = rbind(all_sef, all_seh, all_esf, all_esh)

glimpse(all_se)

## if participants have 
model = glm(all_se$fs_effect ~ all_se$EnglishSpans_boundaryeffect)

model2 = glm(all_se$fs_effect ~ all_se$L3group + all_se$group)

summary(model)
summary(model2)

```


```{r}
## testing models
model = glm(all_se$fs_effect ~ all_se$EnglishSpans_boundaryeffect)

model2 = glm(all_se$fs_effect ~ all_se$L3group + all_se$group)

summary(model)
summary(model2)

mean_se = mean(all_se$EnglishSpans_boundaryeffect)
sd_se = sd(all_se$EnglishSpans_boundaryeffect)

t.test(all_se$eb, all_se$sb, paired = TRUE,)
eb = mean(all_se$eb)
sb = mean(all_se$sb)




```

```{r}

##tidy data

all_se_tidy = all_se %>% 
  pivot_longer(c(`eb`, `sb`, `fb`), names_to = "boundary", values_to = "step")

all_se_tidy2 = all_se %>% 
  pivot_longer(c(`EFBE`, `fs_effect`, `EnglishSpans_boundaryeffect`), names_to = "effects", values_to = "degree")

all_se_tidy3 = unite_(all_se_tidy2, "group", c("L3group","group"))

all_se_tidy = unite_(all_se_tidy, "group", c("L3group","group"))

## look at the L3 span boundary effect per group and order

ggplot(all_se_tidy3, aes(x = effects, y = degree, fill = group)) + geom_boxplot() + ggtitle("Boundary effect per group")

ggplot(all_se_tidy, aes(x = boundary, y = step, fill = group)) + geom_boxplot() + ggtitle("boundary crossing per group")

## T test to see if the differences in ES L3 groups are significant

t.test(all_esf$fs_effect, all_esh$fs_effect)

```
