---
title: "The categorization of L3 sounds in Spanish/English bilinguals during the initial stage of L3 acquisition"
subtitle: 'Spring 2021'
author  : "Kyle Parrish"
date    : "Rutgers University</br>Spring 2021</br>Last update: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: assets
    css: ["rutgers"]
    nature:
      beforeInit: 
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

# Overview 

- Learning an additional language during adulthood is difficult. 

 - This is especially true when one considers phonological acquisition. 

 - Numerous studies over the course of the past five decades have demonstrated that adult second language (L2) learners often produce and perceive the sounds of the target language in a non-native manner (Flege, Yeni-Komshian, and Liu, 1999).

 - This difficulty arises, in part, because bilinguals often navigate complex communicative situations in which they produce and perceive speech from both of their languages in real time. 

---

# Overview 

- Recent studies suggest that bilinguals learn to modify their perceptual categorization routines in accordance with the phonetic realizations of the language they believe they are hearing (Casillas & Simonet, 2018).

- Much less is known about the acquisition of a third language (L3A), particularly with regard to L3 production, perception, and phonological learning. 

- The present investigation explores the perceptual categorization routines of adult bilinguals during the initial stages of L3 acquisition. 

---

# Previous Research 

- Previous studies in L3A have focused primarily on morphosyntax and asked how previously acquired languages interact with the acquisition of a third.

- Some models of L3 morphosyntactic acquisition predict that one single language known by the bilingual influences the L3, but not both.   

- According to these models, the L3 could be influenced by:
 - (1) the L1 only (Hermas, 2014)
 - (2) the L2 only (Bardel & Falk, 2007)
 - (3) either the L1 or the L2 (Rothman, 2015)

- There are also models that suggest that either language may influence a given structure in the L3, but these do not make clear predictions (Westergaard et al., 2017; Slabakova, 2017) 

---

# Previous Research 

- Little is known in L3 phonology, in perception in particular. 

--

.pull-left[
- Findings in L3 production have been mixed. 

--

 - Intermediate VOT values in production
 - L2 influence
]

--

.pull-right[
- Findings in L3 perception.   
 - Liu et al. (2019) L2 influence in perpeption in L1 Chinese L2 English and L3 Spanish speakers
 - Wrembel et al. (2020)

---

For instance, @wrembel_cross-linguistic_2020 found that cross-linguistic influence is structure dependent and varies among individuals, while @balas_perception_2019 found CLI to be modulated by a complex combination of factors such as markedness of the segment under examination, proficiency in the L2 and the L3, and L1 typology. 
Finally, another study on L3 perception in young learners (Polish L1, English L2, German, L3) revealed that the L2 predominantly influences L3 perception in both rhotic sounds and devoicing of word final stops [@wrembel_cross-linguistic_2020]. These variable findings of the source of influence in L3 perception and production, including single language influence, combined languages influence, or structure-dependent influence, point to a lack of homogeneity in multilinguals. 

---

# The Present Study

**Research Questions**

RQ1: Will the double phonemic boundary effect found in previous studies be replicated and extended to vowels?


RQ2: Assuming that bilinguals display the same double phonemic boundary demonstrated in previous studies, will their categorizations of what they believe are the L3 continua resemble their categorizations of either their L1 or their L2? 


RQ3: Will categorizations of what participants believe to be Hungarian or French result in different "language specific" categorization?

---

# The Present Study

**Participants**


---

# The Present Study

**Materials**

---

# The Present Study 

**Procedures**
