---
title: "The categorization of L3 sounds in Spanish/English bilinguals during the initial stage of L3 acquisition"
subtitle: 'Spring 2021'
author  : "Kyle Parrish"
date    : "Rutgers University</br>Spring 2021</br>Last update: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: assets
    css: ["rutgers"]
    nature:
      beforeInit: 
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

# Overview

- Broad questions

- Models of L3A 

- Bilingual Phonology

- Bringing the two together and research questions

- Methods

- Results 

- Discussion 

---

# Broad questions 

.pull-left[
- When a bilingual learns third language, how does it work?
 - How do Spanish-English bilinguals learn a third language? 

- Which language known by a bilingual impacts L3 acquistion? 
 - Will Spanish or English impact the acquistion of the L3, or a combination of both?

- Does it matter which languages a bilingual knows, and which third language they are learning?
 - Does it make a difference if Spanish-English bilinguals learn French versus when they learn Hungarian? 

- Should we expect different linguistic domains, such as morphosyntax and phonology, to be influenced in the same way by previously learned language in an L3 learner? 
 - Models of L3 acquisition have focused on morphosyntax, and the relationship between L3 phonology and morphosyntax remains unclear. 
]

.pull-right[
- Models of L3  
]

---

# Models of L3A 

- Focused on morphosyntax

- TPM

- L2SF

- LPM

- I test these models predictions for L3 phonology

---

# Bilingual Phonology

- To see which language influences the L3, they must have some degree of separation.

- L2 specific phonemes are argued to exist in the literature, although it is challenging for L2 learners to acquire them.

- High proficiency learners have language specific perceptual routines in both the L1 and L2. 

- Language set studies examine the intersection of language mode effects and phoneme categorization and show that bilinguals have language specific categorizations of sounds that is modulated by language mode. 
 
---

# Bilingual Phonology

**Language set studies** 

- Many previous studies in bilingual phonolgoy aimed to demonstrate that a bilingual could categorize the same sound in two different ways under the proper set of circumstances. 

- To do so, a voicing continuum has been used in many studies. 

- English and Spanish differ in the acoustic realization of /p/ and /b/ 
 - English distinguishes long lag unaspirated and short lag aspirated stops, where Spanish prevoices /b/ but not /p/

- These studies predicted that Spanish-English bilinguals would categorize some steps on the same continuum as /p/ when they thought they were hearning Spanish, but /b/ wheb they were told they were hearing English. 

- Several studies have found this effect in Spanish-English bilinguals (referred to as the double phonemic boundary effect)

---

# Bringing the two together and research questions

- Building on previous DPBE studies, I added a third continuum in a "third language", which I told participants was either French or Hungarian. 
 - the stop continuum used in previous studies was used here.
 - A vowel continuum was also created and used in order to evaluate the predictions of full transfer models. 

- It was predicted that Spanish-English bilinguals who show the DPBE would use one of their two perceptual boundaries (the phonology of their L1 or L2) to categorize the L3.

---

# Methods

- Participants

- Materials

- Procedure 

---

# Results 

- logistic regressions

- t.tests

- tosts 

---

# Discussion 

- L3 models were not supported.
 - L1 influence was found in the Spanish L1 group only

- The DPBE was replicated in stops in both groups and extended to vowels in the Spanish L1 group.

- The English L1 group did not show evidence of the DPBE in vowels 

---

# Revisit questions 

.pull-left[
- Which language known by a bilingual impacts L3 acquisition? 
 - The Spanish L1 group provded evidence that the L1 impacts L3A - but the English L1 group might not have shown this result. 

- Does it matter which languages a bilingual knows, and which third language they are learning?
 - Does it make a difference if Spanish-English bilinguals learn French versus when they learn Hungarian? 
  - No differences were found in L3 categorizations in any group, but more data is needed. 

- Should we expect different linguistic domains, such as morphosyntax and phonology, to be influenced in the same way by previously learned language in an L3 learner? 
 - Models of L3 acquisition have focused on morphosyntax, and the relationship between L3 phonology and morphosyntax remains unclear. 
  - These results suggest that phonology and morphosyntax are distinct and should have separate models. 
]
