# Introduction

The present work aims to employ and adapt the methods of recent work in categorical perception to test the predictions of third language (L3) models of morphosyntax and shed light on whether the acquisition of a third language is primarily influenced by either the L1, the L2, or both. In the recent literature on categorical perception in bilinguals, language-specific perception and categorization of sound distinctions of single sounds, such as the difference between /p/ and /b/, were found to be modulated by the language that bilinguals believed that they were hearing [@casillas_perceptual_2018; @gonzales_bafri_2013; @lozano-arguelles_conceptually_2020]. In these studies, the same acoustic continuum was given to participants in 2 alternative forced choice tasks (2afc), but was categorized differently (the boundary between one choice and the other in the task) when the participants were lead to believe that they were hearing English or Spanish. In other words, the same participants categorized the same sound as /p/ when they believed they were listening to Spanish, but /b/ when they believed they were listening to English. 

Following these findings, the present study aims to replicate previous findings and to extend them to a vowel continua. By doing so, the present study adapts the methodology in categorical perception studies to inform L3 models of morphosyntax by having participants complete a third 2-afc in what they will be lead to believe is a third language. Vitally, bilinguals, rather than L3 learners, were chosen for this experiment because the goal was to inform how L3 learners perceive sounds in their third language, and whether this perception is modulated by perceptual routines in one of their known languages. By using participants who do not yet have knowledge of a third language, the potential confound of acquisition of a more independent L3 sound system and cross-linguistic influence from previously known languages is avoided.  

To examine whether the L1 or L2 affects bilinguals' L3 perceptual routines, the participants in the present study categorized a Voice Onset Time (VOT) continuum, and a vowel continuum varying only in the second formant (an F2 continuum). VOT is an acoustic measurement that refers to the relationship between the release of a stop consonant and the onset of vocal fold vibration [@lisker_cross-language_1964]. For example, the difference between [p] and [b] is thought of as a difference in VOT. Where [b] is voiced (a negative VOT), [p] is voiceless (a positive VOT). Languages which contain this distinction, in which there is both a phonetic and phonemic distinction between /p/ and /b/ are referred to as "true-voicing languages" [ @lisker_cross-language_1964]. Relevant to the present study, Spanish, French, and Hungarian fall under this category. English, on the other hand, typically realizes /b/ as voiceless (positive VOT) phonetically, but categorizes it as "voiced" phonemically (as /b/). The phoneme /p/ is also voiceless in English, but is also aspirated, and is categorized by longer VOTs than /b/ [@lisker_cross-language_1964]. These cross-linguistic relationships allow for the testing of the predictions of L3 models of morphosyntax and their extension to L3 perception. 

Much recent research in third language acquisition (L3A) has been primarily concerned with the nature of cross-linguistic influence (CLI) at the initial state of L3 acquisition and has been focused on morphosyntax.
Bilinguals have, by definition, 2 linguistic systems available for transfer when they begin to learn a third language, and the precise role of these languages in L3A has been debated. 
For instance, some scholars have suggested that the second language learned in late bilinguals (those who began the acquisition of the a second language (L2) after childhood) blocks access to the L1, and is the primary influence to the third language (The L2 Status Factor; @bardel_role_2007. 
Others posit that language typology plays a decisive role in determining whether the L1 or the L2 is the primary influence on the third language [@baauw_cognitive_2013; @rothman_l3_2011; @rothman_linguistic_2015; @rothman_typological_2010]. 
In this view, the individual L3 learners’ subconscious impression of cross-linguistic similarity between the languages that they know in comparison to the language that they are learning determines which language primarily influences their L3. Contrary to both the typological and L2 status views, which predict that only a single language transfers to the L3, other models suggest that cross-linguistic influence may occur on a property by property basis [@slabakova_scalpel_2017;@westergaard_crosslinguistic_2017]. 

Importantly, these models have largely received support from empirical studies in morphosyntax, and thus make predictions of morphosyntactic transfer into a third language, rather than language perception. 
It is unclear whether crosslinguistic interactions of phonetics can also be predicted by the L3 morphosyntax models, since they are constrained to a larger degree in their examination of potential gradient effects in L3 learners. 
For instance, two language word orders (SOV vs SVO) can directly and categorically be observed experimentally in L3 learners, in which either L1 word order or L2 word order preference is observed in a single structure of the L3. 
On the other hand, and given the relative lack of gradience in the realization of syntactic transfer (particularly in a single observation), L3 phonetics allow for a more precise examination of the role of the L1 and the L2 to be examined in the production or perception of an acoustic signal. 
For example, measurements of the acoustic realizations of L3 productions of a segment, such as voice-timing in word-initial stop consonants, may provide evidence not only for L1, L2 or property-by-property transfer, but a gradient value, which may also vary by property, and be influenced in tandem by both existing languages in the bilingual mind. 
This information, together with findings in morphosyntax, can paint a clearer picture of the factors which drive CLI and how CLI interacts across phonology and morphosyntax. 

# Literature Review

Broadly, L3 morphosyntax models fall under two categories: full transfer models, which posit that one language is transferred to the L3 at the initial stages of L3A (also referred to as holistic transfer), and property-by-property models [The Linguistic Proximity Model, LPM; @westergaard_crosslinguistic_2017, the Scalpel Model, @slabakova_scalpel_2017]. The body of this literature review will first explain full transfer models of morphosyntax and their empirical evidence, followed property-by-property models. 
Then, studies in L3 phonology will be covered in detail. 
Finally, recent research in categorical perception in bilinguals will be discussed. These studies in the categorization of language specific sounds serve as the methodological basis to the present study.

## Full Transfer models of L3 Morphosyntax

### The Typological Primacy Model

The Typological Primacy Model [TPM; @baauw_cognitive_2013; @rothman_l3_2011; @rothman_linguistic_2015; @rothman_typological_2010] posits that transfer of one grammar holistically occurs in the initial stages of the L3, rather than on a structure-by-structure basis. 
This initial transfer is based on a subconscious “choice” or so called psycho-typology [@kellerman_now_1983] made by the parser based on the cues available in the L3 input. 
In particular, TPM suggests that the hierarchy for the cues used by the L3 learner to determine the typological similarity of languages (and thus which language transfers) is primarily based on cues in the L3 lexicon, followed by phonological/phonotactic information, then by functional morphology and lastly by syntactic structure. 
That is, in the view of the TPM, the L3 learners will first attend to cross-linguistic similarities in the lexicon to which they are exposed via L3 input to make a determination (the L1 or the L2) of which system to transfer to the L3. 
Importantly, this view of the TPM requires that the L3 learner is exposed to input. 
@rothman_linguistic_2015 explains that the “initial stages” of L3A are some 20-25 hours of instruction in a third language, since the L3 learner must be exposed to input before determining similarity between linguistic systems. 
In the context of the present study, perceived typological proximity is predicted to be seen in distinct categorizations of what the participants believe to be French sounds as opposed to Hungarian sounds.

### The L2 Status Factor

The L2 Status Factor [L2SF: @bardel_role_2007; @cabrelli_amaro_l2_2012] posits that the second language learned serves as the source of transfer to a third language by default, regardless of typology. 
Framed within the Declarative/Procedural Model [@paradis_declarative_2009; @paradis_neurolinguistic_2004; @ullman_contributions_2004], the L2SF suggests that the cognitive similarity of the L2 and the L3 may serve as a neurolinguistic explanation for the findings that the L2 transfers by default. 
That is, within the DP model, adult L2 learners rely more heavily on declarative memory than procedural memory to learn the grammar of a new language, as opposed to L1 learning, which is learned in large part by children using procedural memory. 
Since the L3 would likely also involve a higher reliance on declarative memory, it has a higher degree of similarity to the L2, which is thought to drive L2 transfer. 
It is important to note that the L2 Status Factor does not make claims for simultaneous bilinguals who learn a third language later in life, or early trilinguals. 
The claims made by the model refer to late bilinguals, since it is thought that they rely on declarative memory to learn a language. 
However, studies involving the L2 Status Factor have found that it is possible to transfer from the L1, when L3 learners have higher metalinguistic knowledge. 
@falk_role_2015 examined L3 learners of a V2 language (a language that requires a verb to be the second syntactic contituent in a sentence) when their L1 was also a V2 language, and their L2 was a non-V2 language. 
Using a metalinguistic awareness survey, they found that only the participants who scored higher on the survey were able to transfer their L1 V2 properties to the L3 (there was a wide range of non-V2 L2s used in the study).

### Evidence for full transfer models 

Conflicting evidence has been found in support of both of these full transfer models. 
For instance, in a recent meta-analysis of 92 studies in L3 acquisition, @puig-mayenco_systematic_2020 determined that typology (59 out of 92) and L2 status (29 out of 92) were the best predictors of which linguistic system would serve as the basis for a third language. 
However, these findings were not mutually exclusive; the authors coded 25 total studies as being explained both by L2 status and typology, meaning that the results of these studies reported that the L2 transferred to the L3, but could not rule out the possibility that psycho-typological transfer could also explain the results, since the studies did not use mirror image groups (i.e. L3 groups with the same languages, but the opposite order of acquisition). 
An issue with this explanation, however, is the lack of variance in the studies that the authors coded as both typological and L2 transfer, which is predicted to occur by the TPM. 
If typological transfer is individually determined after exposure to L3 input (input which likely is distinct for each L3 learner), and not necessarily a reflection of actual underlying structural similarities [@rothman_linguistic_2015], then some variance would be expected to be observed in populations in which cross-linguistic typology is unclear. 
In other words, one would expect that, based on the predictions of the TPM, that some learners would transfer their L1 and others would transfer their L2, particularly when there is not a clear typological similarity between the languages involved, rather than entire groups transferring solely their L1 or their L2. 

Only one study has reported variance in the choice of the L1 and L2 in L3 acquisition in L3 learners whose order of acquisition was the same (i.e. not mirror image groups seemingly driven by typology). 
In the study on L3 learners of Swedish, @falk_role_2015 found that some learners transferred their L1 and others transferred their L2 in their judgments of V2 sentences. The participants all spoke a V2 L1, and non-V2 L2, but differed in their overall metalinguistic knowledge. 
The study found that  participants with higher metalinguistic knowledge were able to avoid L2 status effects, which would have resulted in non-transfer from their L2, and showed facilitative transfer from L1. Although the authors suggest that this transfer is due to metalinguistic knowledge, rather than underlying perceived psychotypology, these results could also be explained by the TPM, since psycho-typological transfer is made on an individual basis. 

Other studies have found that either the L1 or the L2 may transfer holistically and argue that this is evidence for holistic transfer. In a series of studies investigating the acquisition of L3 Portuguese by Spanish/English bilinguals, Rothman found that Spanish influenced L3 Portuguese, whether it was the L1 or L2 of the participants [@rothman_l3_2011; @rothman_typological_2010]. Other scholar report similar findings, that Spanish is the source of influence in L3 BP in Spanish-English learners of L3 BP [@parma_cross-linguistic_2017; ; @giancaspro_transfer_2015; @peukert_relationship_2015]], or a romance language (Italian or French) and English learning L3 Spanish @foote_transfer_2009]. Similarly, evidence of typologically driven influence was found from French into L3 Spanish in English-French-Spanish trilinguals [@borg_acquisition_2013; @bruhn_de_garavito_subject_2014]. It is important to mention that these studies that empirically support the TPM are exclusively combination of two romance languages (when one is the L3), and English. As a model of third language acquisition, the TPM will need to stand up cross-linguistically.  

Vitally, the findings of these studies do not rule out the possibility of structure-by-structure transfer, since they typically focus on just one property per study. A dissertation that examined multiple syntactic structures in L3 French by Spanish L1 - English L2 and Turkish L1 - English L2 groups did not support the predictions of the TPM [@abbes_acquisition_2016], since the L1 Turkish group showed evidence of both L1 and L2 influence in the results. On the other hand, the Spanish L1 group showed evidence of Spanish being the sole influence on their L3 French, in line with the prediction of the TPM.

The present study engages this issue of the lack of cross-lingusitic support for the TPM by exposing 2 groups of Spanish-English (with both an English and Spanish L1) bilinguals to what they believe is French, a romance language, and what they believe is Hungarian, a non-romance language, with unclear connections to English or Spanish. Based on previous findings, the predictions of the TPM are predicted to be observed in the participants assigned to "French", regardless of their order of acquisition (L1 English or L1 Spanish). On the other hand, it is not predicted that the TPM will be able to explain the results of the Hungarian group, where the typological relationship between the L3 and the known languages of a bilingual is ambiguous. 


## Hybrid Transfer models of L3A

### The Linguistic Proximity Model

Unlike the TPM and the L2SF, the Linguistic Proximity Model [@westergaard_crosslinguistic_2017] suggests that transfer occurs on a property-by-property basis, rather than holistically. 
The LPM suggests that there is a “full transfer possibility”, meaning that any individual structure may transfer at any time, but that it also may not. 
Scholars have argued that this vague prediction creates a problem in modeling L3 transfer acquisition [@bardel_l1_2020; @wrembel_multilingual_2020], since it is unclear when transfer of a particular structure occurs and when it does not. 
Likewise researchers have argued that, unlike the TPM and the L2SF, the LPM is not easily falsifiable [@bardel_l1_2020]. 
Given the lack of predictive power of the LPM, it may only receive post-hoc support. 

In the present study, it is arguable that the categorization of the L3 voice-timing continuum as one language and the categorization of the L3 vowel continuum as the other would provide support for the LPM. However, the precise reasons that a bilingual would categorize the two continua using different, language-specific perceptual boundaries would not be explained by the LPM. Unlike the TPM and L2SF, which make clear predictions, the weakness of the LPM is its unclear criteria for what triggers one language to influence L3 production and perception over the other. In the context of the present study, the LPM would be supported if participants identified the stops in the L3 continuum similarly to their L1, but identified the vowels in the L3 continuum similarly the their L2 (or vice versa). On the other hand, if each participant is found to identify both the L3 stop and vowel continua similarly to one of their two languages, then the LPM would not be supported.

## L3 phonology

### Studies in L3 phonology

Similar to studies in L3 morphosyntax, the few empirical studies to date in L3 phonology has endeavored to identify the source and direction of cross-linguistic influence in the linguistic sound systems of multilinguals, with particular interest in the influence of the two previously acquired systems on the third language system being acquired [@cabrelli_amaro_investigating_2016]. 
Various studies have found a stronger L2 influence on L3 productions at the early stages of L3 acquisition. 

In a case study foundational to L3 phonology, @hammarberg_articulatory_1993 and @hammarberg_processes_2005 examined the productions of a single informant, who spoke L1 British English, L2 German, and L3 Swedish. 
SW, a near-native German speaker as rated by German natives, was recorded reading a story in Swedish at two different time points, first one month after moving to Sweden, and second after one year having lived there. 
Those Swedish recordings at both time points were then judged by native speakers of Swedish with regard to the accent of the speaker in the story, unaware that they were hearing the same informant at two different times. 
Interestingly, the Swedish speakers rated the first telling of the story as heavily German accented (influence from the L2), whereas in recording 2, they rated the accent as coming from an English speaker. 

This initial effect has been referred to as a ‘foreign language effect’ [@meisel_transfer_1983] or, more recently, as L2 status [@bardel_role_2007; @hammarberg_processes_2005]. 
The findings of @hammarberg_processes_2005 suggest that this foreign language effect, or, in other words, the desire to sound less like a speaker of one’s L1, may diminish as proficiency increases and be replaced by L1 effects. 
Other studies have also found primarily L2 influence in L3 productions in global accent ratings [@wrembel_l2-accented_2010], VOT productions [@llama_influence_2010; @tremblay_l2_2007], vowel production [@kamiyama_acquisition_2007] vowel reduction and speech rhythm [@gut_cross-linguistic_2010].

Other findings in L3 phonology production, however, have yielded mixed results. 
Several studies have found that acoustic properties of the participants' productions fall between L1 and L3 values, suggesting that both the L1 and the L2 have some influence on L3 productions, rather than solely one language. 

For instance, [@wrembel_vot_2014] measured VOT and aspiration in all languages of participants with two different language combinations: L1 Polish, L2 English, and L3 French; (2) L1 Polish, L2 English, and L3 German. 
The results showed that each language had a specific stop-value, and that the L3 VOT productions were intermediate, falling between the L1 and L2 values. 
Similarly, [@wrembel_cross-linguistic_2011] examined thirty-two learners of L3 French with L1 Polish and L2 English who were recorded reading lists of words in carrier phrases. 
As in previous studies [@wrembel_vot_2014], combined transfer from the L1 and the L2 in VOT productions was found. 

Findings of combined L1 and L2 influence in VOT productions were also reported by @wunder_phonological_2010 in L3 Spanish speakers, and by @blank_transferencia_2009 in L3 English speakers who spoke L1 Brazilian Portuguese and L2 French. 
Other studies have found an L1 influence on production despite L3 proficiency [@wrembel_foreign_2012], or in advanced L3 learners [@llama_revisiting_2018].

Perception studies in L3 acquisition have been much more scarce than those on production, and primarily in young participants. 
One of few L3 perception studies in adults is @liu_effects_2019, which examined the perceptual boundary of a VOT continuum in trilinguals. 
The participants were L3 spanish speakers who spoke L2 English and L1 Chinese. 
Though the authors focused their analysis on regressive transfer and comparisons to all speakers, the reported boundaries in the study (n = 10, 28ms for Chinese, 24.6ms for English and 23ms for Spanish) suggest that the participants were using their English boundaries for L3 Spanish categorization. 

Other studies in L3 perception, which have examined young trilinguals, have found a wide range of results. 
For instance, @wrembel_cross-linguistic_2020 found that cross-linguistic influence is structure dependent and varies among individuals, while @balas_perception_2019 found CLI to be modulated by a complex combination of factors such as markedness of the segment under examination, proficiency in the L2 and the L3, and L1 typology. 
Finally, another study on L3 perception in young learners (Polish L1, English L2, German, L3) revealed that the L2 predominantly influences L3 perception in both rhotic sounds and devoicing of word final stops [@wrembel_cross-linguistic_2020]. These variable findings of the source of influence in L3 perception and production, including single langauge influence, combined languages influence, or sturcture-dependent influence, point to a lack of homogeneity in multilinguals. 

Firstly, age effects in past studies have varied considerably, in both the age of onset of the L2 and the L3. 
It is worth noting that many studies which report L2 status effects are in adult L3 learners, who have a late age of onset in their L2 [@hammarberg_processes_2005; @wrembel_l2-accented_2010] or this age information was not reported [@gut_cross-linguistic_2010; @kamiyama_acquisition_2007; @tremblay_l2_2007]. 
On the other hand, studies in which L3 learners began their acquisition of their second language at a young age (under 12) tend to show a combined effect of both the L1 and the L2 [@blank_transferencia_2009; @wrembel_cross-linguistic_2011; @wrembel_vot_2014; @wunder_phonological_2010]. 
Although no study has investigated age effects and L3 transfer directly, the L2 Status Factor [@bardel_role_2007] can explain these findings based on the declarative procedural model [DP Model; @paradis_declarative_2009; @paradis_neurolinguistic_2004; @ullman_contributions_2004]. 
Based on the proposed cognitive similarities between late-learned languages in the DP model, the L2 status factor posits that the L2 will transfer to the L3 at the initial stages of acquisition. 
In this view, native language grammars are known implicitly and largely subserved by the procedural memory, whereas late learned language grammars (the L2 and beyond) are thought to be more explicitly known and subserved by the declarative memory. 
Importantly, the L2SF does not make predictions in regard to young bilinguals who learn a third language, precisely because the DP model would predict that both languages of young bilinguals would be implicitly known and both exist in the procedural memory. 
This is in contrast to late bilinguals who learn a third language, whose native language grammar is procedural and whose L2 and L3 are declarative. 

The role of proficiency in both the L2 and the L3 is another vital aspect to language transfer, and has been subject to some controversy among scholars. 
In terms of proficiency in the L2, the DP model suggests that, as proficiency grows, the L2 becomes more subserved by procedural memory, and less dependent on the explicitly driven declarative memory system. 
This gradual shift in dependence may result in a less clear and universal choice of language system to transfer by L2 learners in the beginning stages of L3 acquisition. 
That is, it is possible that late bilinguals who are highly proficient in their L2 may pattern more like early bilinguals than late bilinguals who have lower L2 proficiency. 
Other scholars argue that L2 proficiency must be sufficiently high in order for the L2 to transfer to the L3 [@rothman_linguistic_2015]. 
Taken together, it would seem that a threshold for L2 proficiency is necessary in order for L2 status effects to be observed. 

L3 phonology studies have found conflicting evidence in the role of proficiency, and have focused on the L3, rather than L2 proficiency. 
Some scholars suggest that the L2 serves as the basis for L3 transfer at low levels of L3 proficiency as a sort of ‘coping mechanism’ [See @wrembel_search_2015 for a review]. 
Other studies have found that L2 accented L3 speech is present in low proficiency L3 learners but that higher L3 proficiency speakers show L1 effects in their productions of their L3 [@hammarberg_processes_2005; @wrembel_l2-accented_2010]. 
In sum, both L2 and L3 proficiency levels are vital and must be measured or statistically controlled to determine the precise effect of the proficiency of both languages on CLI. 

Largely, with the exception of the TPM's acknowledgment of the use of phonetic cues in the input to determine cross-linguistic similarity, these models do not consider the role of phonological factors, such as language specific categorization of sounds, on cross-linguistic influence (CLI) in L3A. In principle, the predictions of these L3 morphosyntax models do not explicitly rule out their predictions of syntactic transfer as applying to phonetic CLI. A core tenet of the TPM, for instance, is the concept of cognitive economy, which suggests that one language must be holistically transferred to the L3 due to its relative cognitive ease to transferring many individual structures [@rothman_linguistic_2015]. Following this argument, it is conceivably more cognitively taxing to transfer a single language's syntax and another language's phonology when a bilingual has established language specific categories in phonology and syntax in both languages than it would be to transfer the same language's syntax and phonology together. The L2 Status Factor  


### Categorical Perception

Past research has yielded mixed results in its attempt to demonstrate that bilinguals have language specific perceptual routines, and that the boundary between language specific categories vary as a function of language mode. In other words, in this research paradigm, bilinguals are assumed to have language specific categories of sounds (phonemes), which, in theory, should lead to distinct categorizations of the same acoustic stimuli (such as a step on a VOT continuum) as a function of language mode. 

An initial series of studies focused on VOT and yielded null results. These studies examined the categorization of a /p/-/b/ continuum in two languages. Importantly, this continuum was the same in both sessions, and the hypothesis of these studies was that placing bilinguals in a language specific mode would lead to distinct categorization of the same continuum in two different sessions by the same participant. The initial results showed that in both young French-English bilinguals in Canada [@caramazza_acquisition_1973; @caramazza_bilingual_1974], and Spanish-English bilinguals in the United States [@williams_perception_1977], participants categorized the VOT continuum the same in both language modes. 

By identifying some potential causes of null results in the previous literature, subsequent studies made methodological adjustments and found double phonemic boundary effects in bilinguals that was modulated by language mode. [@elman_perceptual_1977] maintained the use of the same acoustic continuum between languages, but used naturally produced stimul, rather than the synthetic continuum used in previous studies @caramazza_acquisition_1973; @caramazza_bilingual_1974; @williams_perception_1977]. Additionally, Elman et al. argued that simply being placed in a language specific mode does not guarantee its maintenance througout the experimental session. In order to address this, Elman et al. added language specific filler words to keep participants in the approrpiate language mode. As a result, a double phonemic boundary effect was observed in the Spanish-English participants in Elman et al. (1977). Further studies found similar effects in the categorizations of a VOT continuum in French-English [@hazan_perception_1993] and Dutch-English bilinguals [@flege_cross-language_1987]

Subsequent studies examined the role of language proficiency in magnitude of mode effects in bilinguals. @garcia-sierra_testing_2009 found that the double phonemic boundary effect in Spanish-English bilinguals was modulated by proficiency, such that the participants with greater self-reported proficiency made wider distinctions between their mode driven categorizations of the VOT continuum used in the study.

Other studies have maintained language mode by using language specific segments within pseudoword stimuli to perceptually cue a particular language mode [@gonzales_bafri_2013; @casillas_perceptual_2018]. In the original study, @gonzales_bafri_2013 created a VOT continuum using the pseudowords *pafri* and *bafri* as the choices available in a 2-alternative forced choice task. The participants heard a rendition of "parfi" or "bafri in both an English and Spanish session. Rather than language specific filler words, these authors changed the second half of the pseudowords "fri" so that they contained either an English rhotic or Spanish rhotic in each session of the experiment. Importantly, the /pa/-/ba/ first syllable of the pseudowords was identical in both sessions, so that the participants were categorizing pseudowords that had an identical range of VOTs, but distinct, language specific rhotic sounds. The results revealed a double phonemic boundary effect in the Spanish-English bilingual participants with exposure to both languages from early childhood. These results were replicated by @casillas_perceptual_2018, in which the pseudowords pafri-bafri were again used. The findings extended the double phonemic boundary effect to L2 learners, in which higher proficiency L2 learners of Spanish showed stronger L2 boundary effects.

Two follow up studies also investigated the categorization of word initial stops /b/ and /p/ in Spanish-English bilinguals, and young Spanish-English and French-English bilinguals [@gonzales_how_2019].
Differently from @casillas_perceptual_2018 and @gonzales_bafri_2013, these studies presented only the first syllable of the pafri-bafri continuum (paf-baf), and manipulated the participants’ language mode using conceptual cueing by telling participants they were listening to English or Spanish sounds, rather than perceptual cueing of the language specific rhotic sounds used by previous studies. 
The results were consistent with previous studies; sufficiently proficient L2 Spanish speakers show language mode effects in their categorization of /p/ and /b/ on a VOT continuum, whether this is perceptually or conceptually cued. 

The present study will inform models of L3 morphosyntax by examining categorical perception of bilinguals, and determining which of the language specific categorical (phonemic) boudaries Spanish/English bilinguals use to account for L3 sounds at their first exposure.  
Of the L3 morphosyntax models, only the TPM makes predictions in regard to phonological information. 
Namely, it predicts that phonological or phonotactic cues are used to determine typological proximity when lexical overlap cannot readily be detected by the parser in the L3 input [@rothman_linguistic_2015]. 
Since the precise nature of the use of phonological information in the TPM is unclear and untested, the present study presents the same two continua to participants in three different language modes in order to measure their categorization of what they believe to be English, Spanish, and a third language that they do not know. 

## The Present Study

It is this conceptual cuing which resulted in a double phonemic boundary effect found by @lozano-arguelles_conceptually_2020 and @gonzales_how_2019 that motivates the present study. 
Since L3 learners likely detect phonetic cross-linguistic similarities in L3 input, the present study examines the role of conceptual cueing on L3 categorization at the first exposure to L3 input by omitting the presence of language specific segments from the stimuli. 
Following the previous literature, which demonstrates that Spanish-English bilinguals categorize the same continuum of sounds differently depending upon the language they believe they are hearing, the present study both replicates these findings in the /p/-/b/ VOT continuum, extends them to a new F2 /i/-/u/ continuum, and examines whether one of these boundaries are used to categorize sounds in a new language, unknown to the speaker. Additionally, the present study is concerned with whether the third language has a well known historical relationship with previously known languages, and if this affects sound categorization. That is, whether participants who believe they are hearing French will be biased to categorize the continua as similar to their Spanish categorizations. This bias would be argued to be modulated by a metalinguistic knowledge of cross-linguistic similarity and historical relationship between Spanish and French.

In addition to the potential metalinguistic effects on sound categorizations, the language specific acoustic correlates of distinctions between sounds is important, since it can better orient the expected directionality of language specific continua categorization. That is, the typical VOT range in both English and Spanish in which sounds are categorized as /p/ and /b/ is distinct. The difference between /p/ and /b/ in Spanish is one of "true voicing", in which a positive VOT can be observed for the "voiceless" /p/, and a positive VOT is observed in the "voiced" /b/. English, on the other hand, has short and long lag distinction between /p/ and /b/ which is caused by a difference in aspiration. That is, both /p/ and /b/ may be phonetically voiceless (have a positive VOT), but nevertheless be categorized as voiced and voiceless by English speakers.  
French is a true voicing language, which has the lead/short lag distinction [@caramazza_voice_1974; @lisker_cross-language_1964]. Hungarian is considered to be a true-voicing language [@lisker_cross-language_1964], in which a /b/-/p/ distinction is both phonetically and phonemically voiced or voiceless. In the case of the present study, the participants do not have any exposure to a third language, and the language-specific phonetic criteria for both voicing and vowel distinctions are of minimal importance, since the participants will not have had exposure to L3 input. The primary goal of the present study is to determine whether participants use the phonology of their L1 or their L2 when they categorize L3 continua by examining whether a participants' responses in the perceptual task most closely resemble those in their L1, in their L2, or a third, unrelated categorization from the beginning. 

As detailed previously, the entirety of the empirical support for the TPM comes from studies which involve two romance languages and English. 
For this reason, the present study will include a group of this kind (the French L3 group), in which it is expected that the participants will account for these stimuli using their Spanish boundaries, which would partially support TPM, but provide an alternative motivation, namely top-down conceptual cueing, that is behind L3 users choice of language in situations in which typological relationship is evident.
Alternatively, an L3 Hungarian group will also be included, in which the typological relationship between the languages of this group (English, Spanish, and Hungarian) is unclear. 
In this case, the categorization of what participants believe are Hungarian sounds does not have a clearly predictable pattern according to the TPM, and should result in the variable categorization of Hungarian as similar to either the L1 or the L2. Alternatively, it is possible that the Hungarian group will use their second language boundaries to categorize the L3 continua.


#### Research questions

RQ1: Assuming that bilinguals display the same double phonemic boundary demonstrated in previous studies, will their categorizations of what they believe are the L3 continua resemble their categorizations of either their L1 or their L2? 
I hypothesize that that the perception of the “third language” will be modulated by the participants’ order of acquisition in the event that language relatedness is unclear (the Hungarian group), and, alternatively, that participants’ perception will be modulated by their knowledge about the languages relatedness when a clear connection is made between languages at an individual level (the French group). 
In particular, I predict that, when hearing the same continua, participants who are led to believe they are hearing French will perceive it more closely to Spanish than English (as demonstrated  by their perceptual identification of the continua). 
On the other hand, I predict that participants who believe they are hearing Hungarian will categorize sounds by using the phonemic boundary of their second language (L2). 
These predictions are based on findings in previous research on L3 transfer which have demonstrated the default transfer of the L2 to the L3 in language combinations which do not involve romance languages. 

RQ2: Will categorizations of what participants believe to be Hungarian or French result in different "language specific" categorization?
Previous research in L3 syntactic transfer [@baauw_cognitive_2013; @puig-mayenco_systematic_2020; @rothman_typological_2010] has suggested that language transfer to the L3 is not determined by order of acquisition, but by typological similarity of the languages involved. 
The present study offers an alternative account for the data in previous studies by suggesting that the results of previous studies can be explained by a conceptual priming effect that biases the L3 learner to utilize a particular system in order to parse L3 input. 
Based on findings from a systematic review of empirical studies [@puig-mayenco_systematic_2020] in L3 transfer, it appears that there is no evidence of typological transfer outside of Romance language combinations when the third language is not a Romance language. 
Based on this lack of empirical support for the TPM, the present study predicts that Spanish-English bilinguals who believe that they are hearing a romance L3 will be more likely to show bias to perceive it as Spanish-like, rather than English like. 
The design of the present study allows for the teasing apart of typological similarity. 

