# Discussion 

## Summary of findings

The present study attempted to replicate the double phonemic boundary effect in adult Spanish-English bilinguals in both orders of acquisition in two continua, a voicing continuum, and a vowel continuum, in order to investigate how language specific categorization of the continua interacted with a third language at first exposure that the participants did not know, either French or Hungarian. The results showed evidence of L1 influence on L3 categorizations in the Spanish L1 group. This L1 effect was seen in both Spanish L1 L3 groups and in stops and vowels, and was observed in both the French and Hungarian L3 groups. Additionally, the results also showed evidence of L2 influence on L3 categorizations of stops in the English L1 group, but not vowels. Overall, the English L1 group did not show evidence of language specific vowel categorizations.  Finally, the present study replicated the findings of a double phonemic boundary effect found in previous studies [@casillas_perceptual_2018; @gonzales_bafri_2013; @lozano-arguelles_conceptually_2020] in both Spanish L1 bilinguals and English L1 bilinguals, and extended the double phonemic boundary to vowels in the Spanish L1 group. 

## Revisiting the predictions of L3 models

Taken together, the results of the present study cannot be explained by any of the L3 models of morphosyntax alone. The TPM predicted that one language would holistically transfer to the L3, and could be either the L1 or the L2, but not features of both languages. 
The English L1 group provides counter-evidence to this prediction, since they categorized the stop continuum similarly to their L2 categorization, and did not have language distinct categorizations in the vowel continuum. In the view of the TPM, but continua should have been influenced by the same language, rather than the L3 stops being categorized using L1 perceptual boundaries and vowels being categorized using L2 perceptual boundaries. This case was arguably observed in the English L1 group, who categorized vowels similarly in all 3 language contexts, but categorized the L3 stops as similar to their L2.

Additionally, it was expected that the French and Hungarian L3 groups would categorize their L3 differently. In the case of the French group, I predicted that both groups would be biased towards categorizing the L3 continua similarly to their Spanish continua, regardless of their order of acquisition. 
This prediction was based on previous findings in support of the TPM, in which typological transfer was found in language combinations that contained two romance languages and English (with many studies examining Brazilian Portuguese as the L3 in Spanish-English bilinguals). 
Similar evidence has yet to be observed in other language groupings, in which the L1 and the L2 of two different groups (that are the same language) serve as the basis of influence to the L3. This result is conceived of as evidence of typological transfer by the TPM (in the case of syntax). 
Following this lack of cross-linguistic support for the TPM, the Hungarian group was included in the present study, to see whether participant's belief that they were listening to French or Hungarian would differ. 
The predictions of the default source of influence to the Hungarian group's categorizations is much less straightforward than the predictions of the French group. 
In this case, in which there is not a relatively clear typological relationship between two out of three languages in the L3 learner, the literature supports the prediction of L2 status effects by default, meaning that the L2 of the participant would be the source of influence on their L3 categorizations. 

The results of the present study did not confirm either of these predictions. The French and Hungarian groups did not categorize the continua differently in either L1 group. 
In terms of L2 status, the English L1 group showed L2 influence in their categorization of L3 stops in both French and Hungarian, but not in vowels. The result that the English L1 group did not categorize both stops and vowels as similar to the same source of influence (i.e. the L1 or the L2) is incompatible with full transfer models, the TPM and the L2SF. 
In a sense, the LPM can account for this difference, but cannot be said to have predicted it, since the model does not specify clear criteria for when influence does and does not occur. 

## Comparisons to previous language set studies 

The present study was successful in replicating the result of previous studies which found a double phonemic boundary effect in bilinguals [@casillas_perceptual_2018; @gonzales_bafri_2013; @gonzales_how_2019; @lozano-arguelles_conceptually_2020]. In addition to replication, the result of the present study show that it is possible that both L1 Spanish speakers who learn English and L1 English speakers who learn Spanish both have language specific categorizations of sounds based on language context. This effect was found in both groups for stops, and was extended to the vowel continuum in the Spanish L1 group. The English L1 group, on the other hand, did not categorize the vowel continuum differently when they were led to believe that they were hearing English, Spanish or a L3.
The present study used conceptual cueing, as done in @gonzales_how_2019 and @lozano-arguelles_conceptually_2020 , rather than perceptual cueing, to mitigate the possible effect of cross-language segmental similarity biasing perception. As as result, the present study provides a third replication of conceptual cueing in Spanish-English bilinguals in stops. 

On the other hand, it is unclear why the English L1 group did not categorize the vowel continuum distinctly based on language mode. It is possible that the English L1 group has not established stable L2 vowel categories, due to their lower proficiency relative to the Spanish L1 group. On the other hand, it is possible that /u/ fronting in some dialects of English may have biased the results of this group in vowels to have categorized a large part of the continuum in the present study as /u/. Likewise, the context of the experiments between groups could not be carefully and completely controlled due to the challenges of online data collection during the COVID era. It is possible that the English speaking group was simply not as sensitive to the instructions when being biased towards a particular language mode. It is worth noting that the website used for prolific is a British based company, and that the participants using this site may approach it in a default English mode. It is possible that the instructions alone were not a strong enough manipulation to break these participants completely from an English mode. It is worth noting, however that the same participants did categorize the stop continuum differently based on language mode, further complicating the issue. The continua were distinct in that the vowel continuum was produced by a male speaker and the stop continuum was produced by a female speaker. As a result, the average pitch of the vowel continuum was likely lower than the stop continuum. It could be that the English speaking group was sensitive to this pitch difference, where the Spanish group was not.  

## Limitations and Furture Research

These mixed results also may have been caused by the limitations of the present study. A study conducted online likely cannot control for headphones, and the different sound quality among participants' headphones cannot be well controlled for, not ruled out as a possible influence in the results. Likewise, without researcher supervision, participant effort cannot be well evaluated. In the case of the present study, it is unclear whether some participants did no perceive a difference in the steps on the continua due to their phonology or they wanted to complete the experiment as quickly as possible and did not give a genuine effort. Finally, the present study did not control for geographical separation and dialectal variation. The English L1 group contains native speakers of English world wide, including American, British English, and Irish English speakers. The Spanish L1 group, on the other hand, consists of speakers from mostly Mexico, Spain, and Chile. These challenges, together with the low sample size of the present study, suggest that the results reported here be interpreted with caution. 

Future research should consider more carefully the effects of context in online data collection, should this style of data collection continue to be necessary. Limiting a group of participants geographically is vital, since dialectal variation may impact results. In addition, attention checks are helpful for avoiding low effort submissions. 

Theoretically, the evidence from the present study highlights the need to L3 phonology specific studies and models, and the need to carry out experiments in perception and production. The results reported here run contrary to those in production reported in the L3 phonology literature, such as [@hammarberg_articulatory_1993], in which the authors found a global influence of L2 in the beginning of L3 acquisition that eventually was replaced by L1 influence at a later testing time. 
Here, evidence of L2 influence was only found in the English L1 group in stops, while the Spanish L1 group showed evidence of L1 influence on L3 categorizations. 
Further studies are needed to determine whether this asymmetry in production and perception will hold up cross-linguistically, and within the same participants. 
Additionally, given the lack of accurate predictions by L3 models of morphosyntax in L3 perception, further study is needed to determine the factors which influence cross-linguistic influence in L3 perception. 

# Conclusion 

The present study replicated the findings of previous studies that found evidence of conceptually-cued language mode effects in sound categorizations in late bilinguals [@gonzales_how_2019; @lozano-arguelles_conceptually_2020] and, in an extension to previous studies,  found evidence of a double phonemic boundary effect in vowels. 
The predictions of L3 models of morphosyntax were not supported by the evidence of the present study. In particular, the predominant trend in L3 perception was a default L1 influence in the Spanish L1 group, but was the opposite in the English L1 group, where an L2 influence was observed in stops only. 
This L1 influence persisted in both stops and vowels in the Spanish L1 group, and does not support the predictions of any of the L3 models tested here. Moving forward, a model for L3 phonology is likely needed, which should examine and predict both production and perception.
